publication_index:
    path:     /
    defaults: { _controller: "PublicationBundle:Publication:index" }
    methods:  GET

publication_show:
    path:     /show/{id}
    defaults: { _controller: "PublicationBundle:Publication:show" }
    methods:  GET

