publication_show:
    path:     /show/{id}
    defaults: { _controller: "PublicationBundle:Publication:show" }
    methods:  GET

publication_search:
    path:     /search
    defaults: { _controller: "PublicationBundle:Publication:search" }

publication_new:
    path:     /new
    defaults: { _controller: "PublicationBundle:Publication:new" }
    methods:  [GET, POST]

publication_edit:
    path:     /update/{id}
    defaults: { _controller: "PublicationBundle:Publication:edit" }
    methods:  [GET, POST]

publication_list:
    path:     /
    defaults: { _controller: "PublicationBundle:Publication:index" }
    methods:  GET

publication_delete:
    path:     /delete
    defaults: { _controller: "PublicationBundle:Publication:delete" }
    methods:  [POST, GET]
