payment:
    resource: "@PaymentBundle/Resources/config/routing.yml"
    prefix:   /paiement

subscription:
    resource: "@SubscriptionBundle/Resources/config/routing.yml"
    prefix:   /abonnement

publication:
    resource: "@PublicationBundle/Resources/config/routing.yml"
    prefix:   /publication

authentication:
    resource: "@AuthenticationBundle/Resources/config/routing.yml"
    prefix:   /auth

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

