publication:
    resource: "@PublicationBundle/Resources/config/routing.yml"
    prefix:   /publication

authentication:
    resource: "@AuthenticationBundle/Resources/config/routing.yml"
    prefix:   /auth

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

test:
    resource: "@PublicationBundle/Resources/config/routing.yml"
    prefix:   /
