services:
    unamag.tools.service.string:
        class: ToolsBundle\Services\StringService

    unamag.tools.service.search:
        class: ToolsBundle\Services\SearchService
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - '@unamag.tools.service.string'