services:
#    tools.example:
#        class: ToolsBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    unamag.tools.service.string:
        class: ToolsBundle\Services\StringService