<?php

namespace PublicationBundle\Repository;
use AuthenticationBundle\Entity\User;
use Doctrine\ORM\Tools\Pagination\Paginator;
use SubscriptionBundle\Entity\Subscription;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\Security\Core\Exception\BadCredentialsException;
use Symfony\Component\VarDumper\VarDumper;

/**
 * PublicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PublicationRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAll()
    {
        return $this->findBy([], ['id' => 'DESC']);
    }

    public function search($page, $nbMaxParPage, $search = null)
    {
        if (!is_numeric($page)) {
            throw new BadCredentialsException(
                'La valeur de l\'argument $page est incorrecte (valeur : ' . $page . ').'
            );
        }

        if ($page < 1) {
            throw new NotFoundHttpException('La page demandée n\'existe pas');
        }

        if (!is_numeric($nbMaxParPage)) {
            throw new BadCredentialsException(
                'La valeur de l\'argument $nbMaxParPage est incorrecte (valeur : ' . $nbMaxParPage . ').'
            );
        }

        $qb = $this->createQueryBuilder('p');

        if($search != null){
            $qb->where("p.canonicalTitle LIKE '%" .$search. "%'");
        }

        $qb->orderBy('p.id', 'DESC');

        $query = $qb->getQuery();

        $premierResultat = ($page - 1) * $nbMaxParPage;
        $query->setFirstResult($premierResultat)->setMaxResults($nbMaxParPage);
        $paginator = new Paginator($query);

        if ( ($paginator->count() <= $premierResultat) && $page != 1) {
            throw new NotFoundHttpException('La page demandée n\'existe pas.'); // page 404, sauf pour la première page
        }

        return $paginator;
    }

    public function getPublicationByUser(User $user, $limit = 5, $offset = 0, $search = null){
        $userSubscriptions = $user->getSubscription();

        $skiped = [];

        /** @var  $userSubscription Subscription*/
        foreach ($userSubscriptions as $userSubscription){
            $skiped[] = $userSubscription->getPublication()->getId();
        }

        $query = $this->getEntityManager()
            ->createQueryBuilder()
            ->select('p')
            ->from('PublicationBundle:Publication', 'p');

        $searched = false;
        if($search && strlen($search) > 0){
            $searched = true;
            $query->where("p.canonicalTitle LIKE '%" .$search. "%'");
        }

        if(count($skiped) > 0){
            $stringQuery = "p.id NOT IN ( " . implode($skiped, ", ") . " )";
            if($searched){
                $query->andWhere($stringQuery);
            }else{
                $query->where($stringQuery);
            }
        }

        $query->setFirstResult($offset);
        $query->setMaxResults($limit);
        $query->orderBy('p.id', 'DESC');

        return $query->getQuery()->getResult();
    }
}
