parameters:
    database_pgsql: pdo_pgsql
#    api.url: "http://api.unamag.local"
    api.url: "http://10.0.10.116/projet2a/api.unamag.local/web"
    api:
        user:
            get: "%api.url%/user/"
            get_all: "%api.url%/users"
            create: "%api.url%/users/new"
            login: "%api.url%/users/login"
            update: "%api.url%/user/edit"
            activation: "%api.url%/users/actif"
            search: "%api.url%/users/search"
            searchForSub: "%api.url%/users/search/for-subscribe"
        publication:
            get: "%api.url%/publication/show"
            get_all: "%api.url%/publication"
            create: "%api.url%/publication/new"
            update: "%api.url%/publication/update"
            search: "%api.url%/publication/search"
            delete: "%api.url%/publication/delete"
        historical:
            create: "%api.url%/historical/new"
            getAll: "%api.url%/historical/all?userId="
        subscription:
            activation: "%api.url%/subscription/edit/status"
            create: "%api.url%/subscription/new"
            extend: "%api.url%/subscription/edit/extend"
            stopped:
                noRefund: "%api.url%/subscription/stopped/noRefund"
            notPaid: "%api.url%/subscription/notPaid"
        search: "%api.url%/search"
        payment:
            refund: "%api.url%/payment/refund"
            mail: "%api.url%/payment/mail"


