user:
    resource: "@AuthenticationBundle/Resources/config/routing/user.yml"
    prefix:   /user

authentication:
    resource: "@AuthenticationBundle/Resources/config/routing/authentication.yml"
    prefix:   /authentication
