get_user:
    path:     /{id}
    type: rest
    defaults: { _controller: AuthenticationBundle:User:getUser }
    requirements:
            method: GET

get_users:
    path:     /
    defaults: { _controller: AuthenticationBundle:User:getUsers }