<?php

namespace HistoricalBundle\Repository;

/**
 * HistoricalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistoricalRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByUser($userId){
        $query = $this->createQueryBuilder('h')
            ->select('h')
            ->Join('h.users', 'u')
            ->addSelect('u')
            ->Where("u.id = :id ")
            ->setParameter('id', $userId)
            ->orderBy("h.dateCreate","ASC")
            ->getQuery()
            ->getResult();

        return $query;
    }

    public function findGlobal(){
        $query = $this->createQueryBuilder('h')
            ->select('h')
            ->LeftJoin('h.users', 'u')
            ->groupBy('h')
            ->Having('count(u) = 0 ')
            ->orderBy("h.dateCreate","ASC")
            ->getQuery()
            ->getResult();

        return $query;
    }
}
