<?php

namespace HistoricalBundle\Repository;

/**
 * HistoricalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistoricalRepository extends \Doctrine\ORM\EntityRepository
{
}
