parameters:
    api.url: "http://api.unamag.local"
    api:
        user:
            get: "%api.url%/user/"
            get_all: "%api.url%/users"
            create: "%api.url%/users/new"
            login: "%api.url%/users/login"
            update: "%api.url%/user/edit"
        publication:
            get: "%api.url%/publication/show"
            get_all: "%api.url%/publication"
            get_for_user: "%api.url%/publication/for-user"
        activation: "%api.url%/activation"
        subscription:
            get: "%api.url%/subscription/show"
            get_all: "%api.url%/subscriptions"
            get_by_user: "%api.url%/subscriptions/user"
            create: "%api.url%/subscription/new"
            edit_state: "%api.url%/subscription/edit/status"