parameters:
    api.url: "http://api.unamag.local"
    api:
        user:
            get: "%api.url%/user/"
            get_all: "%api.url%/users"
            create: "%api.url%/users/new"
            login: "%api.url%/users/login"
            update: "%api.url%/user/edit"
        publication:
                    get: "%api.url%/publication/show"
                    get_all: "%api.url%/publication"