subscription_homepage:
    path:     /
    defaults: { _controller: SubscriptionBundle:Subscription:index }


subscription_show:
    path:   /changeActif
    defaults: { _controller: SubscriptionBundle:Subscription:changeActif }

subscription_extend:
    path:   /extend
    defaults: { _controller: SubscriptionBundle:Subscription:extend }

subscription_stopNoRefund:
    path:   /stoppedWithoutRefund
    defaults: { _controller: SubscriptionBundle:Subscription:getStoppedSubscriptionWithoutRefund }

subscription_notPaid:
    path:   /notPaid
    defaults: { _controller: SubscriptionBundle:Subscription:notPaid }
