subscription_homepage:
    path:     /
    defaults: { _controller: SubscriptionBundle:Subscription:index }


subscription_show:
    path:   /changeActif
    defaults: { _controller: SubscriptionBundle:Subscription:changeActif }

subscription_new:
    path:   /new
    defaults: { _controller: SubscriptionBundle:Subscription:new }