historical_all:
    path:   /all
    defaults: { _controller: "HistoricalBundle:Historical:index" }
    methods:  GET

historical_new:
    path:   /new
    defaults: { _controller: "HistoricalBundle:Historical:new" }
    methods:  POST