services:
#    publication.example:
#        class: PublicationBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    unamag.service.publication:
        class: PublicationBundle\Services\PublicationService
        arguments:
            - "@doctrine.orm.entity_manager"