authentication_homepage:
    path:     /
    defaults: { _controller: AuthenticationBundle:Auth:index }

authentication_login:
    path:     /login
    defaults: { _controller: AuthenticationBundle:Auth:authenticate }

authentication_logout:
    path:     /logout
    defaults: { _controller: AuthenticationBundle:Auth:logout }