services:
#    authentication.example:
#        class: AuthenticationBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    unamag.service.user:
        class: AuthenticationBundle\Services\UserService
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@security.password_encoder"