AuthenticationBundle\Entity\User:
    properties:
        mail:
            - AuthenticationBundle\Validator\Constraints\ValidMail: ~

        tel:
            - AuthenticationBundle\Validator\Constraints\PhoneFormat: ~

        firstname:
            - AuthenticationBundle\Validator\Constraints\IsString: ~

        lastname:
            - AuthenticationBundle\Validator\Constraints\IsString: ~

        city:
            - AuthenticationBundle\Validator\Constraints\IsString: ~

        birthCity:
            - AuthenticationBundle\Validator\Constraints\IsString: ~

        zipCode:
            - AuthenticationBundle\Validator\Constraints\ZipCode: ~

        birthDate:
            - AuthenticationBundle\Validator\Constraints\BirthDate: ~