subscription:
    resource: "@SubscriptionBundle/Resources/config/routing.yml"
    prefix:   /abonnement

historical:
    resource: "@HistoricalBundle/Resources/config/routing.yml"
    prefix:   /historical

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /users

publication:
    resource: "@PublicationBundle/Resources/config/routing.yml"
    prefix:   /

authentication:
    resource: "@AuthenticationBundle/Resources/config/routing.yml"
    prefix:   /auth

