payment:
    resource: "@PaymentBundle/Resources/config/routing.yml"
    prefix:   /remboursement

subscription:
    resource: "@SubscriptionBundle/Resources/config/routing.yml"
    prefix:   /abonnement

historical:
    resource: "@HistoricalBundle/Resources/config/routing.yml"
    prefix:   /historical

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /users

authentication:
    resource: "@AuthenticationBundle/Resources/config/routing.yml"
    prefix:   /auth

tools:
    resource: "@ToolsBundle/Resources/config/routing.yml"
    prefix:   /tools

publication:
    resource: "@PublicationBundle/Resources/config/routing.yml"
    prefix:   /
