publication_publication:
    resource: "@PublicationBundle/Resources/config/routing/publication.yml"
    prefix:   /

test:
    path:     /admin
    defaults: { _controller: "PublicationBundle:Publication:test" }
