authentication_logout:
    path:     /logout
    defaults: { _controller: AuthenticationBundle:Authentication:logout }

authentication_login:
    path:     /login
    defaults: { _controller: AuthenticationBundle:Security:login }

authentication_create:
    path:     /inscription
    defaults: { _controller: AuthenticationBundle:Authentication:createAccount }