authentication_homepage:
    path:     /
    defaults: { _controller: AuthenticationBundle:Authentication:index }

authentication_create:
    path:     /inscription
    defaults: { _controller: AuthenticationBundle:Authentication:createAccount }