authentication_logout:
    path:     /logout
    defaults: { _controller: AuthenticationBundle:Authentication:logout }

authentication_homepage:
    path:     /
    defaults: { _controller: AuthenticationBundle:Authentication:login }

authentication_create:
    path:     /inscription
    defaults: { _controller: AuthenticationBundle:Authentication:createAccount }