<?php

namespace AuthenticationBundle\Repository;

/**
 * ActivationLinkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActivationLinkRepository extends \Doctrine\ORM\EntityRepository
{
}
