<?php

namespace AuthenticationBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAll()
    {
        return $this->findBy(['level'=>2],['firstname'=> 'ASC' ]); // TODO: Change the autogenerated stub
    }
}
