user_homepage:
    path:     /
    defaults: { _controller: UserBundle:User:index }

user_show:
    path:     /{id}/show
    defaults: { _controller: UserBundle:User:getUser }

user_edit:
    path:     /{id}/edit
    defaults: { _controller: UserBundle:User:editUser }