user_homepage:
    path:     /
    defaults: { _controller: UserBundle:User:index }

user_search:
    path:     /search
    defaults: { _controller: UserBundle:User:search }

user_activation:
    path:     /changeActif
    defaults: { _controller: UserBundle:User:changeActif }

user_show:
    path:     /{id}/show
    defaults: { _controller: UserBundle:User:getUser }

user_edit:
    path:     /{id}/edit
    defaults: { _controller: UserBundle:User:editUser }


