publication_index:
    path:     /
    defaults: { _controller: "PublicationBundle:Publication:index" }
    methods:  GET

publication_show:
    path:     /show
    defaults: { _controller: "PublicationBundle:Publication:show" }
    methods:  GET

publication_new:
    path:     /new
    defaults: { _controller: "PublicationBundle:Publication:new" }
    methods:  [GET, POST]

publication_edit:
    path:     /update
    defaults: { _controller: "PublicationBundle:Publication:edit" }
    methods:  [POST, PUT]

publication_delete:
    path:     /{id}/delete
    defaults: { _controller: "PublicationBundle:Publication:delete" }
    methods:  DELETE

publication_search:
    path:     /search
    defaults: { _controller: "PublicationBundle:Publication:search" }