historical:
    resource: "@HistoricalBundle/Resources/config/routing.yml"
    prefix:   /

subscription:
    type: rest
    resource: "@SubscriptionBundle/Controller/SubscriptionController.php"

user:
    type:     rest
    resource: "@AuthenticationBundle/Controller/UserController.php"
authentication:
    type:     rest
    resource: "@AuthenticationBundle/Controller/AuthController.php"
publication:
    type:     rest
    resource: "@PublicationBundle/Resources/config/routing.yml"
