user:
    type:     rest
    resource: "@AuthenticationBundle/Controller/UserController.php"
authentication:
    type:     rest
    resource: "@AuthenticationBundle/Controller/AuthController.php"
publication:
    type:     rest
    resource: "@PublicationBundle/Resources/config/routing.yml"
